# Generated by Django 2.1 on 2018-10-29 19:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_apicontrol', '0003_auto_20180403_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
