# Generated by Django 3.1.3 on 2020-12-24 22:01

from django.db import migrations, models
import django.utils.timezone
import rest_framework_apicontrol.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_apicontrol', '0009_loggingevent_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='code',
            field=models.CharField(default=rest_framework_apicontrol.utils.generate_random_code, max_length=128),
        ),
        migrations.AlterField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='loggingevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='logginggroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationalunittype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
