# Generated by Django 3.1.3 on 2020-12-26 00:09

from django.db import migrations, models
import rest_framework_apicontrol.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_apicontrol', '0010_auto_20201224_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='code',
            field=models.CharField(default=rest_framework_apicontrol.utils.generate_random_code, max_length=128, unique=True),
        ),
    ]
