# Generated by Django 2.1.2 on 2018-11-20 04:25

from django.db import migrations


def create_default_app(apps, schema_editor):
    App = apps.get_model('rest_framework_apicontrol', 'App')

    App.objects.create(
        code='DEFAULT',
        name='default',
        description='This is the default App instance and it\'s meant to be the default association for related model instances.',
        owner=None,
        metadata={}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_apicontrol', '0011_auto_20201226_0009'),
    ]

    operations = [
        migrations.RunPython(create_default_app),
    ]
